### ISSUE TITLE
Maybe a mistake in the merit computation

### ISSUE THREAD

**Issue by rmontanana** [ZixiaoShen/Correlation-based-Feature-Selection#1]
Hi

Maybe I'm wrong but I think that
```
rff *= 2
```
should be:
```
rff *= (n_features **2 - n_features)
```

in the merit calculation function

Thanks for sharing your code!

**Comment by sazons1** [comment]
The code above did not get the mean value of rff nor rcf, thus rff needn't to *k(k-1) but *2 to accord with the original formula.

**Comment by simonprovost** [comment]
@sazons1 @rmontanana What did you guys agreed on? Nonetheless, I'd like you guys to look at this recent code that seems to take inspiration from this current repository's implementation, yet the number of features are included in the formula here:

https://github.com/Doctorado-ML/mufs/blob/0fdd75405030290c5781be0c47aaf55f82e11ff0/mufs/Selection.py#L137C7-L137C7

Thoughts @rmontanana on your implementation :) ?

**Comment by rmontanana** [comment]
Hi! when I opened this issue, I was only trying to help, stating that in the original paper the formula to compute the merit is this one:

![image](https://github.com/ZixiaoShen/Correlation-based-Feature-Selection/assets/1431097/e6e75f6a-9e58-4324-81b6-78d8c67f830a)

The implementation that @simonprovost mentioned is my own implementation and is not "inspired" in this implementation as anybody can see the code is very different.

**Comment by simonprovost** [comment]
Hi @rmontanana,

I appreciate very much your promptness :) 

> The implementation that @simonprovost mentioned is my own implementation and is not "inspired" in this implementation as anybody can see the code is very different.

While it is evident that your code is not a duplication, it does appear similar from time to time, even beyond the notion. But, all right, all fine :) 

> Hi! when I opened this issue, I was only trying to help, stating that in the original paper the formula to compute the merit is this one (picture)

Indeed ! However, @sazons1 mentioned about the mean. Do you take the mean, as per the equation you forwarded from the paper, in your CFS implementation? `The code above did not get the mean value of rff nor rcf, thus rff needn't to *k(k-1) but *2 to accord with the original formula.`


Cheers mate !

**Comment by simonprovost** [comment]
HI @rmontanana,

If you prefer to be contacted via email for this subject matter, let us know :) 

Have a great start of the week! 

Cheers,

**Comment by simonprovost** [comment]
Hi @rmontanana,

Any news mate ?

Cheers,
